Added SessionService with cookies setup
Solo83/WeatherApp pull request #2
Opened 2024-07-02 13:52 UTC by Solo83

User authorization development

2024-07-07 15:41 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/filter/LoginFilter.java
> +            Arrays.asList("/signin", "/signup", "/home", "")));
Set.of()

2024-07-07 16:00 UTC, Badbadr requested changes

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/filter/LoginFilter.java
> +        if (allowedPath) {
Не совсем понимаю логику. Если путь разрешен - продолжаем цепочку фильров, если путь не разрешен, начинаем манипуляцию с кукисами. Для чего это?

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/service/CookieService.java
> +        Cookie sessionCookie = new Cookie(SESSION_COOKIE, currentSession.getId());
мб шифровать значение?

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/filter/LoginFilter.java
> +        if (session.isEmpty()) {
ifPresentOrElse

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/filter/LoginFilter.java
> +            session = sessionService.getById(sessionId);
Почему сразу не возвращать из сервиса Optional?

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/filter/LoginFilter.java
> +    private void handleInvalidSession(HttpServletRequest req, HttpServletResponse resp, Cookie cookie, String errorMessage) {
Наверное стоит поменять названия методов местами. Этот метод обрабатывает кейс, когда сессии уже нет, то есть она expired, а handleExpiredSession вызывается при условии !sessionValid, то есть когда сессия не валиданя

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/filter/LoginFilter.java
> +            } else {
Если есть варик обойтись без if else, старайся делать это, чтобы код оставался более читаемый. Тут можешь убрать else, в if добавить return;

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/filter/LoginFilter.java
> +    private void handleInvalidSession(HttpServletRequest req, HttpServletResponse resp, Cookie cookie, String errorMessage) {
Не логичнее этот метод поместить в SessionService?

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/filter/LoginFilter.java
> +    private void invalidateCookie(HttpServletResponse resp, Cookie cookie) {
Не логичнее поместить этот мтеод в CookieService?

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/filter/LoginFilter.java
> +    private void handleExpiredSession(HttpServletRequest req, HttpServletResponse resp, Cookie cookie, String sessionId) {
Не логичнее этот метод поместить в SessionService?

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/repository/SessionRepository.java
> +        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
Это селект, для чего тут транзакция?

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/repository/SessionRepository.java
> +            try {
Не удаляй пока, объясни почему поставил ее

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/repository/SessionRepository.java
> +        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
аналогично

2024-07-07 16:00 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/repository/SessionRepository.java
> +        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
аналогично

2024-07-10 15:58 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/controller/SignIn.java
> +            req.setAttribute("user", user);
После try/catch блока дублируется setAttribute

2024-07-10 16:10 UTC, Badbadr commented on src/main/java/com/solo83/weatherapp/controller/SignIn.java
> +            req.setAttribute("user", user);
Ниже снова выставляется атрибут, для чего он выставляется тут?

2024-07-11 08:04 UTC, Solo83 commented on src/main/java/com/solo83/weatherapp/controller/SignIn.java
> +            req.setAttribute("user", user);
Ошибка

2024-07-11 13:53 UTC, merged